routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'PrincipalController@index')->name('principal');
Route::get('/nosotros', 'UsController@index')->name('nosotros');
Route::get('/agregar-al-carro/{product}', 'CartController@add')->name('carro.agregar');
Route::get('/carro-de-compras', 'CartController@index')->name('carro')->middleware('verified');
Route::get('/carro-de-compras/eliminar/{itemId}', 'CartController@destroy')->name('carro.eliminar')->middleware('verified');
Route::get('/carro-de-compras/actualizar/{itemId}', 'CartController@update')->name('carro.actualizar')->middleware('verified');
Route::get('/carro-de-compras/limpiarCarro', 'CartController@clear')->name('carro.limpiar')->middleware('verified');
Route::get('/checkout/{total}/user/{id}', 'CheckoutController@initTransaction')->name('checkout');
Route::post('/checkout/webpay/response', 'CheckoutController@response')->name('checkout.webpay.response');
Route::post('/checkout/webpay/finish', 'CheckoutController@finish')->name('checkout.webpay.finish');
Route::get('/pdfcotizacion', 'PDFController@printPDF')->name('verPDF')->middleware('verified');
Route::get('/mis-compras', 'BuyController@index')->name('compras')->middleware('verified');
Route::get('/detalle-compras/{order}', 'BuyController@show')->name('detalle')->middleware('verified');

Auth::routes(['verify' => true]);

Route::group(['middleware'=>['auth', 'admin']], function(){
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('home/subcategorias', 'SubcategorieController');
    Route::get('home/subcategorias/destroy/{subcategoria}','SubcategorieController@destroy')->name('subcategoria.borrar');
    Route::get('home/subcategorias', 'SubcategorieController@index')->name('subcategorias');
    Route::resource('home/categorias', 'CategorieController');
    Route::get('home/categorias/destroy/{categoria}','CategorieController@destroy')->name('categoria.borrar');
    Route::get('home/categorias', 'CategorieController@index')->name('categorias');
    Route::resource('home/productos', 'ProductController');
    Route::get('home/productos/destroy/{producto}', 'ProductController@destroy')->name('producto.borrar');
    Route::get('home/productos', 'ProductController@index')->name('productos');
    Route::resource('home/temporadas', 'SeasonController');
    Route::get('home/temporadas/destroy/{temporada}', 'SeasonController@destroy')->name('temporada.borrar');
    Route::get('home/temporadas', 'SeasonController@index')->name('temporadas');
    Route::resource('home/redes', 'SocialController');
    Route::get('home/redes', 'SocialController@index')->name('redes');
    Route::get('home/redes/destroy/{rede}', 'SocialController@destroy')->name('red.borrar');
    Route::resource('home/imagenes', 'ProductImagesController');
    Route::get('home/imagenes', 'ProductImagesController@index')->name('imagenes');
    Route::get('home/imagenes/destroy/{imagene}', 'ProductImagesController@destroy')->name('imagenes.borrar');
    Route::resource('home/informacion', 'InformationController');
    Route::get('home/informacion', 'InformationController@index')->name('informacion');
    Route::resource('home/orden', 'OrderController');
    Route::get('home/orden', 'OrderController@index')->name('orden');
});

resources/views/crudProducto/agregarProducto.blade.php
@extends('layouts.plantillaHome')

@section('content')
@include('common.errors')
<div class="row justify-content-center">
        <div class="col-12 col-lg-12 pb-5">
             <form id="form" class="form-group" method="POST" action="/home/productos" enctype="multipart/form-data">
                    @csrf
                      <div class="card shadow-lg">
                          <div class="card-header bg-primary p-0">
                              <div class="text-white text-center py-2">
                                  <h3 class="font-weight-bold"> Registro de producto</h3>
                              </div>
                          </div>
                          <div class="card-body p-0 my-3">
                              <div class="form-group col-12 col-lg-10 mx-auto">
                                  <div class="input-group mb-2 my-3 mx-auto">
                                      <div class="input-group-prepend">
                                          <div class="input-group-text bg-gradient-primary"><i class="fa fa-tags text-white"></i></div>
                                      </div>
                                    <input aria-label="Nombre" id="validationName" type="text" name="name" class="form-control" value="{{old('name')}}" placeholder="Ingrese el nombre" required pattern="[A-Za-z0-9 ]+" title="Solo se admiten letras y números.">
                                  </div>
                                  <div class="input-group mb-2 my-3 mx-auto">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text bg-gradient-primary">  <i class="fas fa-pen-alt text-white"></i> </div>
                                    </div>
                                <textarea aria-label="Descripción" id="validationDescription" name="description" class="form-control" placeholder="Ingrese la descripción" required>{{old('description')}}</textarea>
                                    </div>
                                    <div class="row">
                                        <div class="col-12 col-md-6">
                                            <div class="input-group mb-2 mx-auto">
                                                <div class="input-group-prepend">
                                                    <div class="input-group-text bg-gradient-primary"><i class="fa fa-dollar-sign text-white"></i></div>
                                                </div>
                                            <input aria-label="Precio" id="validationPrice"type="number"  onkeydown="javascript: return event.keyCode === 8 ||
                                                event.keyCode === 46 ? true : !isNaN(Number(event.key))" name="price" class="form-control" value="{{old('price')}}" placeholder="Ingrese el precio" required>
                                            </div>
                                        </div>
                                        <div class="col-12 col-md-6">
                                            <div class="input-group mb-2 mx-auto">
                                                <div class="input-group-prepend">
                                                    <div class="input-group-text bg-gradient-primary"><i class="fa fa-plus text-white"></i></div>
                                                </div>
                                            <input aria-label="Stock" id="validationStock"  onkeydown="javascript: return event.keyCode === 8 ||
                                                event.keyCode === 46 ? true : !isNaN(Number(event.key))" type="number" name="stock" class="form-control" value="{{old('stock')}}" placeholder="Ingrese el stock" required>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="input-group mb-2 my-2 mx-auto">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text bg-gradient-primary"> <i class="fa fa-tag text-white"></i> </div>
                                        </div>
                                        <select aria-label="Categoría" id="validationCategorie" class="custom-select" name="subcategorie_id" required>
                                          <option disabled selected value="">-- Escoga una subcategoría --</option>
                                            @if (isset($subcategories) && $subcategories ?? '')
                                                @foreach ($subcategories as $sc)
                                                    <option value="{{$sc->id}}" {{ old('subcategorie_id') == $sc->id ? 'selected' : '' }}> {{$sc->categorie->name}} - {{$sc->name}}</option>
                                                    
                                                @endforeach
                                            @endif
                                        </select>
                                    </div>
                                    <div class="input-group mb-2 my-1 mx-auto">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text bg-gradient-primary"> <i class="fa fa-tags text-white"></i> </div>
                                    </div>
                                    <select aria-label="Temporada" class="custom-select" name="season_id">
                                      <option disabled selected>-- Escoga una temporada --</option>
                                      @if (isset($seasons) && $seasons ?? '')
                                        @foreach ($seasons as $s)
                                            <option value="{{$s->id}}" {{old('season_id') == $s->id ? 'selected' : ''}}>{{$s->name}}</option>
                                        @endforeach   
                                      @endif
                                    </select>
                                </div>
                                    <small class="text-primary">La temporada puede quedar <b>vacía</b></small>
                                 <div class="input-group mb-2 my-1 mx-auto">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text bg-gradient-primary"> <i class="fa fa-star text-white"></i> </div>
                                    </div>
                                    <select aria-label="Destacado" id="validationDestacated" class="custom-select" name="destacated" required>
                                      <option disabled selected value="">-- ¿Es un producto destacado? --</option>
                                          <option value="si" {{old('destacated') == "si" ? 'selected' : ''}}>Sí</option>
                                          <option value="no" {{old('destacated') == "no" ? 'selected' : ''}}>No</option>
                                    </select>
                                </div>
                                <label class="d-block text-dark" for="Imagen">Imagen</label>
                                <div class="row">
                                    <div class="col-12 col-md-6">
                                        <div class="custom-file uploadfrm">
                                            <input type="file" accept="image/*" name="image" class="custom-file-input" onchange="readURL(this);" required>
                                            <label class="custom-file-label" data-browse="Imagen">Suba su imagen</label>
                                        </div>
                                    <small class="text-primary d-block my-1">La imagen no debe superar los <b>2 MB</b></small>
                                    </div>
                                    <div class="col-12 col-md-6 text-center">
                                        <div class="preview">
                                            <img id="img-preview" src="http://placehold.it/150x150" alt="Vista previa" height="150" width="150" class="img-thumbnail border-0">
                                            <small class="d-block">Vista previa de su imagen</small>
                                        </div>
                                    </div>
                                </div>
                                <div class="mx-auto my-4">
                                    <a href="{{route('productos')}}" class="btn btn-light mx-auto my-1"> <i class="fa fa-arrow-left mr-2"></i>Volver</a>
                                    <button id="btnSubmit" class="btn btn-primary ml-2 mx-auto">Guardar <i class="fa fa-cloud-upload-alt ml-2"></i></button>
                                  </div>  
                              </div>         
                          </div>
                      </div>
                  </form>
              </div>
        </div>  
@endsection
@section('scripts')
<script>
function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#img-preview')
                        .attr('src', e.target.result);
                };
                reader.readAsDataURL(input.files[0]);
            }
        }
</script>
@endsection

resources/views/crudProducto/listaProducto.blade.php
@extends('layouts.plantillaHome')

@section('content')
    <div class="card shadow mb-4">
        <div class="card-header bg-primary py-3">
          <h5 class="m-0 font-weight-bold text-white">Listado de productos</h5>
        </div>
        <div class="card-body">
          <div class="container-fluid">
            <!-- Barra de busqueda -->
          <form class="col-sm-8 col-md-8 col-lg-6 d-none d-sm-inline-block p-0">
            <div class="input-group">
              <input type="text" name="searchproduct" class="form-control border small text-dark" placeholder="¿Qué buscas?" aria-label="Buscador">
              <div class="input-group-append">
              <button aria-label="Buscador" class="btn btn-primary" type="submit">
                  <i class="fas fa-search fa-sm"></i>
              </button>
              </div>
            </div>
          </form>
          <ul class="navbar-nav ml-auto">
            <!-- Boton para abrir la barra de busqueda -->
            <li class="nav-item dropdown no-arrow d-sm-none text-right">
              <a class="nav-link dropdown-toggle" aria-label="Buscador" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw fa-2x text-primary"></i>
              </a>
              <!-- Fin Boton para abrir la barra de busqueda -->
              <!-- Barra de busqueda en pantallas pequeñas -->
              <div class="dropdown-menu dropdown-menu p-3 shadow" aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                  <div class="input-group">
                    <input type="text" name="searchproduct" class="form-control border small text-dark" placeholder="¿Qué buscas?" aria-label="Buscador">
                    <div class="input-group-append">
                      <button aria-label="Buscador" class="btn btn-primary" type="submit">
                        <i class="fas fa-search fa-sm"></i>
                      </button>
                    </div>
                  </div>
                </form>
              </div>
                <!-- Fin Barra de busqueda en pantallas pequeñas -->
            </li>
          </ul>
           <!-- Resultados de búsqueda-->
            <div class="my-2">
              @if(isset($query) && $query ?? '') 
                <div class="alert alert-success">
                  <h6 class="d-inline">
                    @if (isset($products) && $products->count() > 0)
                      Los resultados para <h6 class="font-weight-bold d-inline">"{{$query}}"</h6> son:  
                    @else
                      No existen resultados para: <h6 class="font-weight-bold d-inline">"{{$query}}"</h6> 
                    @endif
                  </h6>
                </div>
                <div class="d-flex justify-content-start">
                  <a href="{{route('productos')}}" type="submit" role="button" class="btn btn-outline-primary">Mostrar todos</a>
                </div>
              @endif
          </div>
              @include('common.success')
               <!-- Fin Resultados de búsqueda-->
              <div class="text-right my-1 p-0">
                <a href="{{route('productos.create')}}" role="button" type="button" class="btn btn-primary text-white">Agregar <span class="fa fa-plus-circle"></span></a>
              </div>
              <div class="row">
                @if (isset($products) && $products ?? '')
                  @foreach ($products as $product)
                  <div class="col-auto col-sm-6 col-md-6 col-lg-4 col-xl-3 mx-auto text-dark my-1">
                    <div class="card shadow h-100">
                    <!-- src=/images/productos/{{$product->image}} -->
                    <img class="card-img-top" src="{{$product->image}}" width="240" height="231" title="{{'Imagend de '.$product->name}}" alt="{{'Imagend de '.$product->name}}">
                      <div class="card-body">
                      <h5 title="{{$product->name}}" class="card-title font-weight-bold text-uppercase">{{Str::limit($product->name, $limit="12", $end="...")}}</h5>
                      <a href="{{route('productos.show', $product->slug)}}" class="btn btn-outline-primary font-weight-bold">Ver más</a>     
                      <div class="text-left">
                        <a aria-label="Editar" title="Editar" href="{{route('productos.edit', $product->slug)}}" class="btn btn-info text-white text-center my-2 mr-2"> <span class="fa fa-edit"></span></a>
                        <a aria-label="Eliminar" title="Eliminar" data-toggle="modal" data-target="#openModal{{$product->id}}" role="button" type="button" class="btn btn-danger text-white"> <span class="fa fa-trash text-white"></span></a>
                        <div class="modal fade" id="openModal{{$product->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                          <div class="modal-dialog" role="document">
                            <div class="modal-content">
                              <div class="modal-header bg-primary text-white">
                                <h5 class="modal-title font-weight-bold" id="exampleModalLabel">Eliminar producto</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                  <span class="text-white active" aria-hidden="true">&times;</span>
                                </button>
                                </div>
                                <div class="modal-body font-weight-bold">
                                  <div class="text-center">
                                    <i class="fa fa-exclamation-triangle fa-2x text-primary"></i>
                                  </div>
                                  ¿Está seguro de eliminar este producto: "{{$product->name}}" ?
                                </div>
                                <div class="modal-footer">
                                  <button type="button" class="btn btn-light" data-dismiss="modal">Cancelar</button>
                                  <a href="{{route('producto.borrar', $product->slug)}}" type="button" class="btn btn-primary">Sí, eliminar <span class="fa fa-trash ml-2"></span> </a>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      </div>
                    </div>
                  </div>
                  @endforeach  
                @endif
              </div>
              <div class="d-flex justify-content-center my-4">
                @if (isset($products) && $products ?? '')
                  {{$products->links()}}        
                @endif
              </div>
            </div>
          </div>
        </div>
@endsection

resources/views/crudProducto/mostrarProducto.blade.php
@extends('layouts.plantillaHome')

@section('content')
      <div class="card shadow-lg mb-4">
        <div class="card-header bg-primary py-3">
          <h5 class="m-0 font-weight-bold text-white">Descripción de producto</h5>
        </div>
        <div class="card-body text-dark">
          <div class="container-fluid">
          <div class="text-center">
          <div class="card border-0" >
            <div class="row">
              <div class="col-md-4">
                @if (isset($product) && $product ?? '')
                      @foreach ($product as $p)
                        <img height="220" width="220" class="img-fluid mx-auto d-block my-5" src="{{$p->image}}" alt="{{'Imagen de '.$p->name}}" title="{{'Imagen de '.$p->name}}">
                        </div>
                          <div class="col-auto col-lg-8 col-xl-8 my-2">
                            <h2 class="card-title text-center font-weight-bold text-uppercase">{{$p->name}}</h2>
                            <div class="row">
                              <div class="col-lg-6 col-xl-6 mx-auto text-left">
                              <h4 class="card-subtitle font-weight-bold">{{$p->description}}</h4>
                              <h3 class="card-text font-weight-bold text-danger">$ {{$p->price}}</h3>
                              <h5 class="card-text font-weight-bold">Stock: {{$p->stock}}</h5>
                              </div>
                              <div class="col-lg-6 col-xl-6 mx-auto text-left">
                                @if ($p->destacated == 'si')
                                <h5 class="badge badge-primary text-wrap py-3 text-uppercase mr-2">Producto destacado <i class="fa fa-star text-white"></i> </h5>
                                @else
                                <h5 class="badge badge-danger text-wrap py-3 text-uppercase">Producto no destacado </h5>
                                @endif
                              <h5 class="badge badge-warning text-wrap py-3 text-uppercase">{{$p->subcategorie->categorie->name}} - {{$p->subcategorie->name}} </h5>
                              @if ($p->season->name ?? '')
                              <h5 class="badge badge-info text-wrap py-3 text-uppercase">Temporada de {{$p->season->name}}</h5>
                              @else
                              <h5 class="badge badge-danger text-wrap py-3 text-uppercase">Sin temporada</h5>
                              @endif
                              </div>
                            </div>
                          </div>
                           <div class="col-12 text-center">
                              <div class="card-subtitle font-weight-bold">Modificado el: {{$p->updated_at}}</div>
                              <div class="row">
                                <div class="col-6 text-left">
                                  <a href="{{route('productos')}}" class="text-left btn btn-light mx-auto my-1 card-link"> <i class="fa fa-arrow-left mr-2"></i>Volver</a>
                               </div>
                                 <div class="col-6 text-right">
                                   <a href="{{route('productos.edit', $p->slug)}}" class="btn btn-info text-center my-2 text-white">Editar <span class="fa fa-edit"></span></a>
                                   <a data-toggle="modal" data-target="#openModal{{$p->id}}" role="button" type="button" class="btn btn-danger text-center text-white">Eliminar <span class="fa fa-trash"></span></a>
                                 </div>

                              </div>
                           </div>
                      </div>
                    </div>
                  </div>
                  </div>
                </div>
              </div>
              <!-- Modal -->
              <div class="modal fade" id="openModal{{$p->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header bg-primary text-white">
                      <h5 class="modal-title font-weight-bold" id="exampleModalLabel">Eliminar producto</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span class="text-white active" aria-hidden="true">&times;</span>
                      </button>
                      </div>
                      <div class="modal-body font-weight-bold">
                        <div class="text-center">
                          <i class="fa fa-exclamation-triangle fa-2x text-primary"></i>
                        </div>
                        ¿Está seguro de eliminar este producto: "{{$p->name}}" ?
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-light" data-dismiss="modal">Cancelar</button>
                        <a href="{{route('producto.borrar',$p->slug)}}" type="button" class="btn btn-primary">Sí, eliminar <span class="fa fa-trash ml-2"></span> </a>
                    </div>
                  </div>
                </div>
              </div>
                @endforeach
      @endif
@endsection