routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'PrincipalController@index')->name('principal');
Route::get('/nosotros', 'UsController@index')->name('nosotros');
Route::get('/agregar-al-carro/{product}', 'CartController@add')->name('carro.agregar');
Route::get('/carro-de-compras', 'CartController@index')->name('carro')->middleware('verified');
Route::get('/carro-de-compras/eliminar/{itemId}', 'CartController@destroy')->name('carro.eliminar')->middleware('verified');
Route::get('/carro-de-compras/actualizar/{itemId}', 'CartController@update')->name('carro.actualizar')->middleware('verified');
Route::get('/carro-de-compras/limpiarCarro', 'CartController@clear')->name('carro.limpiar')->middleware('verified');
Route::get('/checkout/{total}/user/{id}', 'CheckoutController@initTransaction')->name('checkout');
Route::post('/checkout/webpay/response', 'CheckoutController@response')->name('checkout.webpay.response');
Route::post('/checkout/webpay/finish', 'CheckoutController@finish')->name('checkout.webpay.finish');
Route::get('/pdfcotizacion', 'PDFController@printPDF')->name('verPDF')->middleware('verified');
Route::get('/mis-compras', 'BuyController@index')->name('compras')->middleware('verified');
Route::get('/detalle-compras/{order}', 'BuyController@show')->name('detalle')->middleware('verified');

Auth::routes(['verify' => true]);

Route::group(['middleware'=>['auth', 'admin']], function(){
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('home/subcategorias', 'SubcategorieController');
    Route::get('home/subcategorias/destroy/{subcategoria}','SubcategorieController@destroy')->name('subcategoria.borrar');
    Route::get('home/subcategorias', 'SubcategorieController@index')->name('subcategorias');
    Route::resource('home/categorias', 'CategorieController');
    Route::get('home/categorias/destroy/{categoria}','CategorieController@destroy')->name('categoria.borrar');
    Route::get('home/categorias', 'CategorieController@index')->name('categorias');
    Route::resource('home/productos', 'ProductController');
    Route::get('home/productos/destroy/{producto}', 'ProductController@destroy')->name('producto.borrar');
    Route::get('home/productos', 'ProductController@index')->name('productos');
    Route::resource('home/temporadas', 'SeasonController');
    Route::get('home/temporadas/destroy/{temporada}', 'SeasonController@destroy')->name('temporada.borrar');
    Route::get('home/temporadas', 'SeasonController@index')->name('temporadas');
    Route::resource('home/redes', 'SocialController');
    Route::get('home/redes', 'SocialController@index')->name('redes');
    Route::get('home/redes/destroy/{rede}', 'SocialController@destroy')->name('red.borrar');
    Route::resource('home/imagenes', 'ProductImagesController');
    Route::get('home/imagenes', 'ProductImagesController@index')->name('imagenes');
    Route::get('home/imagenes/destroy/{imagene}', 'ProductImagesController@destroy')->name('imagenes.borrar');
    Route::resource('home/informacion', 'InformationController');
    Route::get('home/informacion', 'InformationController@index')->name('informacion');
    Route::resource('home/orden', 'OrderController');
    Route::get('home/orden', 'OrderController@index')->name('orden');
});

resources/views/crudInformacion/agregarInformacion.blade.php
@extends('layouts.plantillaHome')

@section('content')
@include('common.errors')
<div class="row justify-content-center">
        <div class="col-12 col-lg-12 pb-5">
            <form class="form-group" method="POST" action="/home/informacion" enctype="multipart/form-data">
                    @csrf
                      <div class="card shadow-lg">
                          <div class="card-header bg-primary p-0">
                              <div class="text-white text-center py-2">
                                  <h3 class="font-weight-bold"> Registro de información empresarial</h3>
                              </div>
                          </div>
                          <div class="card-body p-3">
                            <div class="card mb-3">
                                <div class="card-header font-weight-bold bg-primary text-white">Horarios</div>
                                <div class="card-body text-dark">
                                    <div class="form-group col-12 col-lg-5 mx-auto d-inline-block">
                                        <label  class="d-block" for="normal_working_hours_start">Horario normal (Inicio)</label>
                                        <div class="input-group mb-2">
                                            <div class="input-group-prepend">
                                                <div class="input-group-text bg-gradient-primary"><i class="fa fa-clock text-white"></i></div>
                                            </div>
                                        <input aria-label="Horario normal" type="time" id="validationStart1" name="normal_working_hours_start" value="{{old('normal_working_hours_start')}}" class="form-control clockpicker" readonly required>
                                        </div>
                                    </div>
                                    <div class="form-group col-12 col-lg-5 mx-auto d-inline-block">
                                        <label  class="d-block" for="normal_working_hours_end">Horario normal (Fin)</label>
                                        <div class="input-group mb-2">
                                            <div class="input-group-prepend">
                                                <div class="input-group-text bg-gradient-primary"><i class="fa fa-clock text-white"></i></div>
                                            </div>
                                        <input aria-label="Horario normal" type="time" id="validationEnd1" name="normal_working_hours_end" class="form-control clockpicker" value="{{old('normal_working_hours_end')}}" readonly required>
                                        </div>
                                    </div>
                                    <div class="form-group col-12 col-lg-5 mx-auto d-inline-block">
                                        <label class="d-block" for="working_hours_sunday_start">Horario Domingo (Inicio)</label>
                                        <div class="input-group mb-2">
                                            <div class="input-group-prepend">
                                                <div class="input-group-text bg-gradient-primary"><i class="fa fa-clock text-white"></i></div>
                                            </div>
                                        <input aria-label="Horario Domingo" type="time" id="validationStart2" name="working_hours_sunday_start" class="form-control clockpicker" value="{{old('working_hours_sunday_start')}}" readonly required>
                                        </div>
                                    </div>
                                    <div class="form-group col-12 col-lg-5 mx-auto d-inline-block">
                                        <label class="d-block" for="working_hours_sunday_end">Horario Domingo (Fin)</label>
                                        <div class="input-group mb-2">
                                            <div class="input-group-prepend">
                                                <div class="input-group-text bg-gradient-primary"><i class="fa fa-clock text-white"></i></div>
                                            </div>
                                        <input aria-label="Horario Domingo" type="time" id="validationEnd2" name="working_hours_sunday_end" class="form-control clockpicker" value="{{old('working_hours_sunday_end')}}" readonly required>
                                        </div>
                                    </div>
                                    <div class="form-group col-12 col-lg-5 mx-auto d-inline-block">
                                        <label class="d-block" for="holidays_working_hours_start">Horario Festivos (Inicio)</label>
                                        <div class="input-group mb-2">
                                            <div class="input-group-prepend">
                                                <div class="input-group-text bg-gradient-primary"><i class="fa fa-clock text-white"></i></div>
                                            </div>
                                        <input aria-label="Horario festivos" type="time" id="validationStart3" name="holidays_working_hours_start" class="form-control clockpicker" value="{{old('holidays_working_hours_start')}}" readonly required>
                                        </div>
                                    </div>
                                    <div class="form-group col-12 col-lg-5 mx-auto d-inline-block">
                                        <label class="d-block" for="holidays_working_hours_end">Horario Festivos (Fin)</label>
                                        <div class="input-group mb-2">
                                            <div class="input-group-prepend">
                                                <div class="input-group-text bg-gradient-primary"><i class="fa fa-clock text-white"></i></div>
                                            </div>
                                        <input aria-label="Horario festivos" type="time" id="validationEnd3" name="holidays_working_hours_end" class="form-control clockpicker" value="{{old('holidays_working_hours_end')}}" readonly required>
                                        </div>
                                    </div>
                                </div>
                              </div>
                            <div class="card mb-3">
                                <div class="card-header font-weight-bold bg-primary text-white">Nuestros valores</div>
                                <div class="card-body text-dark">
                                    <div class="form-group col-12 col-lg-11 mx-auto">
                                        <div class="input-group mb-2">
                                            <div class="input-group-prepend">
                                                <div class="input-group-text bg-gradient-primary"><i class="fa fa-heart text-white"></i></div>
                                            </div>
                                        <textarea aria-label="Misión" type="text" id="validationMission" name="mission" class="form-control" placeholder="Ingrese la misión" required>{{old('mission')}}</textarea>
                                        </div>
                                        <div class="input-group mb-2">
                                            <div class="input-group-prepend">
                                                <div class="input-group-text bg-gradient-primary"><i class="fa fa-heart text-white"></i></div>
                                            </div>
                                        <textarea aria-label="Visión" type="text" id="validationVision" name="vision" class="form-control" placeholder="Ingrese la visión" required>{{old('vision')}}</textarea>
                                        </div>
                                    </div>
                                </div>
                              </div>
                            <div class="card border mb-3">
                                <div class="card-header font-weight-bold bg-primary text-white">Descripción de nuestra empresa</div>
                                <div class="card-body text-dark">
                                    <div class="form-group col-12 col-lg-11 mx-auto">
                                        <div class="input-group mb-2">
                                            <div class="input-group-prepend">
                                                <div class="input-group-text bg-gradient-primary"><i class="fa fa-pencil-alt text-white"></i></div>
                                            </div>
                                        <textarea aria-label="Descripción" type="text" id="validationDescription" name="description" class="form-control" placeholder="Ingrese la descripción de su empresa" required>{{old('description')}}</textarea>
                                        </div>
                                    </div>
                                </div>
                              </div>
                            <div class="card border mb-3">
                                <div class="card-header font-weight-bold bg-primary text-white">Nuestra ubicación</div>
                                <div class="card-body text-dark">
                                    <div class="form-group col-12 col-lg-11 mx-auto">
                                        <div class="input-group mb-2">
                                            <div class="input-group-prepend">
                                                <div class="input-group-text bg-gradient-primary"><i class="fa fa-map-marker-alt text-white"></i></div>
                                            </div>
                                        <input aria-label="Ubiación" type="text" id="validationUbication" name="ubication" class="form-control" value="{{old('ubication')}}" placeholder="Ingrese la ubicación" required>
                                        </div>
                                    </div>
                                </div>
                              </div>
                              <div class="mx-auto my-4">
                                <a href="{{route('informacion')}}" class="btn btn-light"> <i class="fa fa-arrow-left mr-2"></i>Volver</a>
                                <button id="btnSubmit" class="btn btn-primary ml-2">Guardar <i class="fa fa-cloud-upload-alt ml-2"></i></button>
                              </div>
                          </div>
                      </div>
                  </form>
              </div>
        </div>
@endsection
@section('scripts')
    <script src="{{asset('js/clockpicker.js')}}"></script>
    <script src="{{asset('js/openClockPicker.js')}}"></script>
@endsection

resources/views/crudInformacion/listaInformacion.blade.php
@extends('layouts.plantillaHome')
@section('content')
        <div class="card shadow-lg mb-4">
            <div class="card-header bg-primary text-white py-3">
              <h4 class="m-0 font-weight-bold">Panel de administración de información empresarial</h4>
            </div>
            <div class="card-body">
              <div class="container-fluid">
              @include('common.success')
              @if (isset($information) && $information->count() == 0)
                <div class="text-right my-1 p-0">
                  <a href="{{route('informacion.create')}}" role="button" type="button" class="btn btn-primary text-white">Agregar <span class="fa fa-plus-circle"></span></a>
                </div>
              @else
                <div class="text-right my-1 p-0">
                <a role="button" type="button" class="btn btn-primary text-white disabled" aria-disabled="true">Agregar <span class="fa fa-plus-circle"></span></a>
                </div>
              @endif
              <div class="row">
                @if (isset($information) && $information ?? '')
                  @foreach ($information as $info)
                  <div class="col-lg-5">
                    <div class="card">
                        <div class="card-header font-weight-bold bg-primary text-white">Horarios</div>
                        <div class="card-body text-dark">
                            <ul class="list-unstyled">
                            <li><a class="font-weight-bold"><i class="fas fa-clock fa-2x mr-2 text-primary"></i>Horario normal: {{$info->normal_working_hours}}</a></li>
                            <li><a class="font-weight-bold"><i class="fas fa-clock fa-2x mr-2 text-primary"></i>Horario Domingo: {{$info->working_hours_sunday}}</a></li>
                            <li><a class="font-weight-bold"><i class="fas fa-clock fa-2x mr-2 text-primary"></i>Horario Festivo: {{$info->holidays_working_hours}}</a></li>
                            </ul>
                        </div>
                      </div>
                  </div>
                  <div class="col-lg-7">
                    <div class="card mb-3 my-1">
                        <div class="card-header font-weight-bold bg-primary text-white">Nuestros valores</div>
                        <div class="card-body text-dark">
                            <div class="row">
                            <div class="col-lg-6 my-2">
                                <div class="card text-center">
                                    <a>
                                        <i class="fa fa-heart fa-4x text-primary my-1"></i>
                                        <h3 class="m-b-xs"><strong>Misión</strong></h3>
                                    </a>
                                    <div class="card-footer bg-gradient-primary text-white">
                                        {{$info->mission}}
                                    </div>    
                                </div>
                            </div>
                            <div class="col-lg-6 my-2">
                                <div class="card text-center">
                                    <a>
                                        <i class="fa fa-heart fa-4x text-primary my-1"></i>
                                        <h3 class="m-b-xs"><strong>Visión</strong></h3>
                                    </a>
                                    <div class="card-footer bg-gradient-primary text-white">
                                        {{$info->vision}}
                                    </div>
                                </div>
                            </div>
                        </div>
                        </div>
                      </div>
                  </div>
                  <div class="col-lg-5">
                    <div class="card border mb-3">
                        <div class="card-header font-weight-bold bg-primary text-white">Sobre nosotros</div>
                        <div class="card-body text-dark">
                          <div class="card-text">{{$info->description}}</div>
                        </div>
                      </div>
                  </div>
                  <div class="col-lg-7">
                    <div class="card border mb-3">
                        <div class="card-header font-weight-bold bg-primary text-white">Nuestra ubicación</div>
                        <div class="card-body text-dark">
                            <div class="card-text">
                                {{$info->ubication}}
                            </div>
                        </div>
                      </div>
                  </div>
                  <div class="col-lg-12 mx-auto">
                    <div class="d-flex justify-content-end">
                      <a href="{{route('informacion.edit', $info->id)}}" role="button" type="button" class="btn btn-info text-white">Editar <span class="fa fa-edit"></span></a>
                    </div>
                  </div>
                  @endforeach
                @endif
              </div>
            </div>
          </div>
        </div>   
@endsection