routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'PrincipalController@index')->name('principal');
Route::get('/nosotros', 'UsController@index')->name('nosotros');
Route::get('/agregar-al-carro/{product}', 'CartController@add')->name('carro.agregar');
Route::get('/carro-de-compras', 'CartController@index')->name('carro')->middleware('verified');
Route::get('/carro-de-compras/eliminar/{itemId}', 'CartController@destroy')->name('carro.eliminar')->middleware('verified');
Route::get('/carro-de-compras/actualizar/{itemId}', 'CartController@update')->name('carro.actualizar')->middleware('verified');
Route::get('/carro-de-compras/limpiarCarro', 'CartController@clear')->name('carro.limpiar')->middleware('verified');
Route::get('/checkout/{total}/user/{id}', 'CheckoutController@initTransaction')->name('checkout');
Route::post('/checkout/webpay/response', 'CheckoutController@response')->name('checkout.webpay.response');
Route::post('/checkout/webpay/finish', 'CheckoutController@finish')->name('checkout.webpay.finish');
Route::get('/pdfcotizacion', 'PDFController@printPDF')->name('verPDF')->middleware('verified');
Route::get('/mis-compras', 'BuyController@index')->name('compras')->middleware('verified');
Route::get('/detalle-compras/{order}', 'BuyController@show')->name('detalle')->middleware('verified');

Auth::routes(['verify' => true]);

Route::group(['middleware'=>['auth', 'admin']], function(){
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('home/subcategorias', 'SubcategorieController');
    Route::get('home/subcategorias/destroy/{subcategoria}','SubcategorieController@destroy')->name('subcategoria.borrar');
    Route::get('home/subcategorias', 'SubcategorieController@index')->name('subcategorias');
    Route::resource('home/categorias', 'CategorieController');
    Route::get('home/categorias/destroy/{categoria}','CategorieController@destroy')->name('categoria.borrar');
    Route::get('home/categorias', 'CategorieController@index')->name('categorias');
    Route::resource('home/productos', 'ProductController');
    Route::get('home/productos/destroy/{producto}', 'ProductController@destroy')->name('producto.borrar');
    Route::get('home/productos', 'ProductController@index')->name('productos');
    Route::resource('home/temporadas', 'SeasonController');
    Route::get('home/temporadas/destroy/{temporada}', 'SeasonController@destroy')->name('temporada.borrar');
    Route::get('home/temporadas', 'SeasonController@index')->name('temporadas');
    Route::resource('home/redes', 'SocialController');
    Route::get('home/redes', 'SocialController@index')->name('redes');
    Route::get('home/redes/destroy/{rede}', 'SocialController@destroy')->name('red.borrar');
    Route::resource('home/imagenes', 'ProductImagesController');
    Route::get('home/imagenes', 'ProductImagesController@index')->name('imagenes');
    Route::get('home/imagenes/destroy/{imagene}', 'ProductImagesController@destroy')->name('imagenes.borrar');
    Route::resource('home/informacion', 'InformationController');
    Route::get('home/informacion', 'InformationController@index')->name('informacion');
    Route::resource('home/orden', 'OrderController');
    Route::get('home/orden', 'OrderController@index')->name('orden');
});

resources/views/crudSubcategoria/agregarSubcategoria.blade.php
@extends('layouts.plantillaHome')

@section('content')
<div class="row justify-content-center">
 @include('common.errors')
  <div class="col-12 col-lg-12 pb-5">
              <form id="form" class="form-group" method="POST" action="/home/subcategorias" enctype="multipart/form-data">
                    @csrf
                      <div class="card shadow-lg">
                          <div class="card-header bg-primary p-0">
                              <div class="text-white text-center py-2">
                                  <h3 class="font-weight-bold"> Registro de subcategorías</h3>
                              </div>
                          </div>
                          <div class="card-body p-0 my-3">
                              <div class="form-group col-12 col-lg-11 mx-auto">
                              <label class="text-dark font-weight-bold d-block d-sm-none" for="Nombre">Nombre de la subcategoría</label>
                                  <div class="input-group mb-2">
                                      <div class="input-group-prepend">
                                          <div class="input-group-text bg-gradient-primary"><i class="fa fa-tags text-white"></i></div>
                                      </div>
                                    <input aria-label="Nombre" id="validationName" type="text" name="name" class="form-control" value="{{old('name')}}" placeholder="Nombre de la subcategoría" required pattern="[A-Za-z0-9 ]+" title="Solo se admiten letras y números.">
                                  </div>
                                  <label class="text-dark font-weight-bold d-block d-sm-none" for="NombreCategoria">Seleccione la categoría</label>
                                  <div class="input-group mb-2">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text bg-gradient-primary"> <i class="fa fa-tag text-white"></i> </div>
                                    </div>
                                    <select aria-label="Categoría" id="validationCategorie" class="custom-select" name="categorie_id" required>
                                      <option disabled selected value="">-- Seleccione una categoría --</option>
                                      @if (isset($categories) && $categories ?? '')
                                        @foreach ($categories as $c)
                                            <option  value="{{$c->id}}" {{old('categorie_id') == $c->id ? 'selected': ''}}>{{$c->name}}</option>
                                        @endforeach
                                      @endif
                                    </select>
                                </div>
                                <div class="mx-auto my-4">
                                    <a href="{{route('subcategorias')}}" class="btn btn-light mx-auto my-1"> <i class="fa fa-arrow-left mr-2"></i>Volver</a>
                                    <button id="btnSubmit" class="btn btn-primary ml-2 mx-auto">Guardar <i class="fa fa-cloud-upload-alt ml-2"></i></button>
                                 </div>
                              </div>
                          </div>
                      </div>
                  </form>
              </div>
        </div>
@endsection

resources/views/crudSubcategoria/editarSubcategoria.blade.php
@extends('layouts.plantillaHome')

@section('content')
@include('common.errors')
<div class="row justify-content-center">
      <div class="col-12 col-lg-12 pb-5">
          @if (isset($subcategorie) && $subcategorie ?? '') 
            <form id="form" class="form-group" method="POST" action="/home/subcategorias/{{$subcategorie->slug}}" enctype="multipart/form-data">
                    @method('PUT')
                        @csrf
                                <div class="card shadow-lg">
                                    <div class="card-header bg-primary p-0">
                                        <div class="text-white text-center py-2">
                                            <h3 class="font-weight-bold"> Actualización de subcategorías</h3>
                                        </div>
                                    </div>
                                    <div class="card-body p-0 my-2">
                                        <div class="form-group col-12 col-lg-11 mx-auto">
                                            <label class="d-block text-dark font-weight-bold" for="name">Nombre de subcategoría</label>
                                            <div class="input-group mb-2">
                                                <div class="input-group-prepend">
                                                    <div class="input-group-text bg-gradient-primary"><i class="fa fa-tags text-white"></i></div>
                                                </div>
                                                <input aria-label="Nombre" id="validationName" type="text" name="name" value="{{$subcategorie->name}}" class="form-control" placeholder="Ingrese el nombre" required pattern="[A-Za-z0-9 ]+" title="Solo se admiten letras y números.">
                                            </div>
                                            <label class="d-block text-dark font-weight-bold" for="categorie_id">Categoría</label>
                                        <div class="input-group mb-2">
                                            <div class="input-group-prepend">
                                                <div class="input-group-text bg-gradient-primary"> <i class="fa fa-tag text-white"></i> </div>
                                            </div>
                                            <select aria-label="Categoría" class="custom-select" name="categorie_id" required>
                                                @if (isset($categories) && $categories ?? '')
                                                    @foreach ($categories as $c)
                                                        <option  value="{{$c->id}}" @if(isset($subcategorie->categorie_id) && $c->id == $subcategorie->categorie_id) selected @endif>
                                                            {{$c->name}}
                                                        </option>
                                                    @endforeach 
                                                @endif
                                            </select>
                                            </div>
                                            <div class="mx-auto my-4">
                                            <a href="{{route('subcategorias')}}" class="btn btn-light mx-auto my-1"> <i class="fa fa-arrow-left mr-2"></i>Volver</a>
                                            <button id="btnSubmit" class="btn btn-primary ml-2 mx-auto">Actualizar <i class="fa fa-cloud-upload-alt ml-2"></i></button>
                                        </div>  
                                        </div>
                                    </div>
                                </div>
                            </form>
                        @endif
                  </div>
            </div>    
@endsection

resources/views/crudSubcategoria/listaSubcategoria.blade.php
@extends('layouts.plantillaHome')

@section('content')
          <div class="card shadow-lg mb-4">
            <div class="card-header bg-primary py-3">
              <h5 class="m-0 font-weight-bold text-white">Panel de administración de subcategorías</h5>
            </div>
            <div class="card-body">
              <div class="container-fluid">
                <!-- Barra de busqueda -->
              <form class="col-sm-8 col-md-8 col-lg-6 d-none d-sm-inline-block p-0">
                <div class="input-group">
                  <input type="text" name="searchsubcategorie" class="form-control border small text-dark" placeholder="¿Qué buscas?" aria-label="Buscador">
                  <div class="input-group-append">
                    <button aria-label="Buscador" class="btn btn-primary" type="submit">
                      <i class="fas fa-search fa-sm"></i>
                    </button>
                  </div>
                </div>
              </form>
          <ul class="navbar-nav ml-auto">
            <!-- Boton para abrir la barra de busqueda -->
            <li class="nav-item dropdown no-arrow d-sm-none text-right">
              <a class="nav-link dropdown-toggle" aria-label="Buscador" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw fa-2x text-primary"></i>
              </a>
              <!-- Fin Boton para abrir la barra de busqueda -->
              <!-- Barra de busqueda en pantallas pequeñas -->
              <div class="dropdown-menu dropdown-menu p-3 shadow" aria-label="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                  <div class="input-group">
                    <input type="text" name="searchsubcategorie" class="form-control border small text-dark" placeholder="¿Qué buscas?" aria-label="Buscador">
                    <div class="input-group-append">
                      <button aria-label="Buscador" class="btn btn-primary" type="submit">
                        <i class="fas fa-search fa-sm"></i>
                      </button>
                    </div>
                  </div>
                </form>
              </div>
                <!-- Fin Barra de busqueda en pantallas pequeñas -->
            </li>
          </ul>
           <!-- Resultados de búsqueda-->
              <div class="my-2">
                @if(isset($query) && $query ?? '') 
                  <div class="alert alert-success">
                    <h6 class="d-inline">
                      @if (isset($subcategories) && $subcategories->count() > 0)
                        Los resultados para <h6 class="font-weight-bold d-inline">"{{$query}}"</h6> son:  
                      @else
                        No existen resultados para: <h6 class="font-weight-bold d-inline">"{{$query}}"</h6> 
                      @endif
                    </h6>
                  </div>
                  <div class="d-flex justify-content-start">
                    <a href="{{route('subcategorias')}}" type="submit" role="button" class="btn btn-outline-primary">Mostrar todas</a>
                  </div>
                @endif
            </div>
               <!-- Fin Resultados de búsqueda-->
               @include('common.success')
              <div class="table-responsive">
                <table class="table text-dark font-weight-bold" id="dataTable" width="100%" cellspacing="0">
                    <div class="text-right my-1 p-0">
                        <a href="{{route('subcategorias.create')}}" role="button" type="button" class="btn btn-primary text-white">Agregar <span class="fa fa-plus-circle"></span></a>
                    </div>
                  <thead class="bg-gradient-primary text-white">
                    <tr>
                      <th>Nombre</th>
                      <th>Categoría</th>
                      <th>Opciones</th>
                    </tr>
                  </thead>
                  <tfoot class="bg-gradient-primary text-white">
                    <tr>
                      <th>Nombre</th>
                      <th>Categoría</th>
                      <th>Opciones</th>
                    </tr>
                  </tfoot>
                  <tbody>
                    @if (isset($subcategories) && $subcategories ?? '') 
                      @foreach ($subcategories as $subcategorie)
                      <tr>
                      <td>{{$subcategorie->name}}</td>
                      <td>{{$subcategorie->categorie->name}}</td>
                      <td>
                      <a aria-label="Editar" href="{{route('subcategorias.edit', $subcategorie->slug)}}" role="button" type="button" class="btn btn-info text-white my-1"><span class="fa fa-edit"></span></a> 
                      <a aria-label="Eliminar" data-toggle="modal" data-target="#openModal{{$subcategorie->id}}" role="button" type="button" class="btn btn-danger"> <span class="fa fa-trash text-white"></span></a>
                      <div class="modal fade" id="openModal{{$subcategorie->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                          <div class="modal-content">
                            <div class="modal-header bg-primary text-white">
                              <h5 class="modal-title font-weight-bold" id="exampleModalLabel">Eliminar subcategoría</h5>
                              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span class="text-white active" aria-hidden="true">&times;</span>
                              </button>
                              </div>
                              <div class="modal-body font-weight-bold">
                                <div class="text-center">
                                  <i class="fa fa-exclamation-triangle fa-2x text-primary"></i>
                                </div>
                                ¿Está seguro de eliminar esta subcategoría: "{{$subcategorie->name}}" ?
                              </div>
                              <div class="modal-footer">
                                <button type="button" class="btn btn-light" data-dismiss="modal">Cancelar</button>
                                <a href="{{route('subcategoria.borrar',$subcategorie->slug)}}" type="button" class="btn btn-primary">Sí, eliminar <span class="fa fa-trash ml-2"></span> </a>
                            </div>
                          </div>
                        </div>
                      </div>
                      </td>
                      </tr>
                      @endforeach
                    @endif
                  </tbody>
                </table>
                <div class="d-flex justify-content-center">
                  @if (isset($subcategories) && $subcategories ?? '')
                    {{$subcategories->links()}}  
                  @endif
                </div>
              </div>
            </div>
          </div>
        </div> 
@endsection